### PR TITLE
updated several items to address false positives

### PR DESCRIPTION
**Pull request by bullmoose20**

### CODE REVIEW

**Comment by chazlarson** [comment]
I left no validation on position because it's more complicated than just "left" or "right".

language:
> position: Values: List of Coordinates

flixpatrol:
> position: Values: right, left, or List of Coordinates

I have no idea yet how to validate a "list of coordinates", and if it's limited to "right", "left", then coordinates aren't acceptable, so "languages" won't validate at all.

**Comment by bullmoose20** [comment]
> I left no validation on position because it's more complicated than just "left" or "right".
> 
> language:
> 
> > position: Values: List of Coordinates
> 
> flixpatrol:
> 
> > position: Values: right, left, or List of Coordinates
> 
> I have no idea yet how to validate a "list of coordinates", and if it's limited to "right", "left", then coordinates aren't acceptable, so "languages" won't validate at all.

I think position was just not found at all.....I added it and possibly made it too restrictive by only stating left or right. The reason is because I saw this error show up under my flixpatrol template_variables. So I went to flixpatrol and saw the only options were left, right. I did not see a mention of List of Coordinates on the wiki <https://metamanager.wiki/en/nightly/defaults/overlays/flixpatrol.html>

**Comment by chazlarson** [comment]
flixpatrol page:

image

language flags:

image

**Comment by chazlarson** [comment]
`delete_collections` isn't a boolean:
<https://metamanager.wiki/en/nightly/config/operations.html#delete-collections>

**Comment by bullmoose20** [comment]
a couple of my "fixes" are slightly better than the previous version, however still have issues. delete_collections for example... and looks like you saw that as well and pointed it out. I did not know how to add delete_collections and then specify that the two option below had to be boolean and not delete_collections itself

**Comment by bullmoose20** [comment]
and you already commented on that part...

**Comment by chazlarson** [comment]
> a couple of my "fixes" are slightly better than the previous version, however still have issues. delete_collections for example... and looks like you saw that as well and pointed it out. I did not know how to add delete_collections and then specify that the two option below had to be boolean and not delete_collections itself

Sure, and that's why I just left it out for now.  If it's in there as a boolean, then it's enforcing incorrect syntax, and correct syntax will fail.

Same thing with `position`.  If it's in there as true/false, then correct syntax will fail.

**Comment by bullmoose20** [comment]
> > a couple of my "fixes" are slightly better than the previous version, however still have issues. delete_collections for example... and looks like you saw that as well and pointed it out. I did not know how to add delete_collections and then specify that the two option below had to be boolean and not delete_collections itself
> 
> Sure, and that's why I just left it out for now. If it's in there as a boolean, then it's enforcing incorrect syntax, and correct syntax will fail.
> 
> Same thing with `position`. If it's in there as true/false, then correct syntax will fail.

Right... so position left/right would be fine as long as List of Coordinates was not used... as soon as that is used, then it will report an error.

    overlay_path:
    - remove_overlays: false                        # Set to true if you want to remove overlays
    - reapply_overlays: false                       # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays
    - reset_overlays: tmdb                          # if you want to reset the poster to default poster from tmdb

These are also partially fixed... however I think there is something overall going on that causes this to fail. If I do not use pmm:, then file: or other valid pmm schema items fail. It seems to always want pmm:

image

**Comment by bullmoose20** [comment]
I have not attempted this, however, it looks like rating could benefit from having something in the schema:
image

Probably a pattern? Not sure you even attempted this since I don't think you use ratings in your config

**Comment by bullmoose20** [comment]
this is also an interesting error in PMM:
[2023-07-31 18:31:22,396] [config.py:389]             [WARNING]  | Config Warning: tmdb sub-attribute region: None is an invalid input using None as default          |

So the schema has all the country codes as per PMM, however, None is not acceptable, but it is as per the message. So I think in this case, a null value or blank is acceptable. Not sure how to add a null value in the schema

**Comment by chazlarson** [comment]
> so position left/right would be fine as long as List of Coordinates was not used

It would be fine here:
```
      - pmm: flixpatrol
        template_variables:
          position: << right, left, or List of Coordinates >>
```
but not here:
```
      - pmm: languages
        template_variables:
          position: << List of Coordinates >>
```

The problem is that for one of the two `position`s, left/right aren't valid, so if the only schema-accepted values are left/right, then that use [in `languages`] will pass the schema and then fail in use.

**Comment by chazlarson** [comment]
> Probably a pattern? Not sure you even attempted this since I don't think you use ratings in your config

I'm not basing this on things I use in my config.  I started with the example config file.  Things that aren't in there are because I hadn't gotten to them or hadn't researched how to validate the construction.

The goal would be to have this be comprehensive.

**Pull request merged**
